# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
countries = Country.create([{ name: "China", us_imports: "29.8", min_wage: "156", poverty: "11.2", country_image: "china.png", people_image: "chinaPeople.png" }, { name: "Vientnam", us_imports: "9.3", min_wage: "90", poverty: "4.8", country_image: "vietnam.png", people_image: "vietnamPeople.png" }, { name: "India", us_imports: "3.4", min_wage: "70", poverty: "21.3", country_image: "india.png", people_image: "indiaPeople.png" }, { name: "Bangladesh", us_imports: "4.8", min_wage: "68", poverty: "43.7", country_image: "bangladesh.png", people_image: "bangladeshPeople.png" }, { name: "Indonesia", us_imports: "4.8", min_wage: "74", poverty: "15.9", country_image: "indonesia.png", people_image: "indonesiaPeople.png" }, { name: "Mexico", us_imports: "3.7", min_wage: "127", poverty: "3.8", country_image: "mexico.png", people_image: "mexicoPeople.png" }, { name: "Honduras", us_imports: "2.6", min_wage: "339", poverty: "15.5", country_image: "honduras.png", people_image: "hondurasPeople.png" }, { name: "Cambodia", us_imports: "2.5", min_wage: "100", poverty: "9.97", country_image: "cambodia.png", people_image: "cambodiaPeople.png" }, { name: "El Salvador", us_imports: "1.9", min_wage: "203", poverty: "7.24", country_image: "el_salvador.png", people_image: "el_salvadorPeople.png" }, { name: "Sri Lanka", us_imports: "1.8", min_wage: "66", poverty: "1.7", country_image: "sri_lanka.png", people_image: "sri_lankaPeople.png" }])

visitors = Visitor.create([{ guess: 'China', tshirt_made: 'China'}, { guess: 'Vietnam', tshirt_made: 'Vietnam'}, { guess: 'Bangladesh', tshirt_made: 'Bangladesh'}, { guess: 'Indonesia', tshirt_made: 'Indonesia'}, { guess: 'Mexico', tshirt_made: 'Mexico'}, { guess: 'India', tshirt_made: 'India'}, { guess: 'Honduras', tshirt_made: 'Honduras'}, { guess: 'Cambodia', tshirt_made: 'Cambodia'}, { guess: 'El Salvador', tshirt_made: 'El Salvador'}, { guess: 'Sri Lanka', tshirt_made: 'Sri Lanka'}, { guess: 'United States', tshirt_made: 'United States'}, { guess: 'Hand-Made', tshirt_made: 'Hand-Made'}, { guess: 'Other', tshirt_made: 'Other'}])
